version: "2"

services:

  data_store:
    env_file: .env
    image: postgres:9.6
    container_name: data-store
    ports:
      - "5432:5432"
    volumes:
      - /var/pdata/:/var/lib/postgresql/data

  ngeobackend:
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ngeo-backend
    links:
      - data_store:data_store
    depends_on:
      - data_store
    ports:
      - "4000:4000"
